### ISSUE TITLE
Is this pressflow 6 fork still supported? 

### ISSUE THREAD

**Issue by osopolar** [omega8cc/pressflow6#7]
In the pressflow/6 issue I asked: [Is Pressflow 6 LTS still supported? #130](https://github.com/pressflow/6/issues/130) and I was pointed to this fork:

> There is always some delay in syncing Pressflow 6 with Drupal 6 LTS, but you can always use our Pressflow 6 fork we maintain for many years, which also includes many improvements in comparison to vanilla Pressflow 6: https://github.com/omega8cc/pressflow6/releases

Now I am wondering about the same problem: Is this Pressflow fork still supported?

**Comment by omega8cc** [comment]
Yes, it's slower than usual, but we will update our fork this week.

**Comment by omega8cc** [comment]
Yes, Pressflow 6.56.2 has been released. We will make sure it gets any further updates faster. Thanks!
