### ISSUE TITLE
Warning: substr() expects parameter 1 to be string, array given in includes/database.inc on line 358

### ISSUE THREAD

**Issue by osopolar** [omega8cc/pressflow6#8]
After updating to the latest version 6.57.1 I got the warning:

> Warning: substr() expects parameter 1 to be string, array given in includes/database.inc on line 358

I wonder what happened to this drupal 6 LTS core commit, its missing in pressflow:
https://github.com/d6lts/drupal/pull/40/commits/e90fafbe34272cc013a303c2436c062337cc531e

**Comment by osopolar** [comment]
See also d.o. issue [db_version_compare() does not handle if $db_url is an array](https://www.drupal.org/project/d6lts/issues/3052207) and https://github.com/d6lts/drupal/pull/40

**Comment by osopolar** [comment]
@omega8cc Any news on this?

**Comment by omega8cc** [comment]
This patch was not included before because it's not compatible with Pressflow and needs adjustments. You can't use the d6lts patch partially either, just patching function `db_version_compare()` without patching `function db_set_active()`, so this needs more work.

**Comment by osopolar** [comment]
Thanks for fixing this. I haven't seen that `function db_set_active()` needed a fix too. Maybe it was not relevant in my setup. I am using this changes, but haven't had problems so far. But I will update now.
